import { District } from 'src/app/model/District';

export const allDistricts: District[] = [
  { name: 'Colombo', value: 1 },
  { name: 'Kandy', value: 2 },
  { name: 'Gampaha', value: 3 },
  { name: 'Kalutara', value: 4 },
  { name: 'Galle', value: 5 },
  { name: 'Matara', value: 6 },
  { name: 'Hambantota', value: 7 },
  { name: 'Jaffna', value: 8 },
  { name: 'Kilinochchi', value: 9 },
  { name: 'Mannar', value: 10 },
  { name: 'Mullaitivu', value: 11 },
  { name: 'Vavuniya', value: 12 },
  { name: 'Puttalam', value: 13 },
  { name: 'Kurunegala', value: 14 },
  { name: 'Anuradhapura', value: 15 },
  { name: 'Polonnaruwa', value: 16 },
  { name: 'Matale', value: 17 },
  { name: 'Nuwara Eliya', value: 18 },
  { name: 'Kegalle', value: 19 },
  { name: 'Ratnapura', value: 20 },
  { name: 'Trincomalee', value: 21 },
  { name: 'Batticaloa', value: 22 },
  { name: 'Ampara', value: 23 },
  { name: 'Badulla', value: 24 },
  { name: 'Monaragala', value: 25 },
];
